from distutils.core import setup

setup(name='gripit',
      version='0.0.1',
      py_module=['gripit'],
      install_requires=['connectorx',
                        'contextily',
                        'fiona',
                        'folium',
                        'geopandas',
                        'networkx',
                        'osmnx',
                        'polars',
                        'pandas',
                        'numpy',
                        'pyscopg2',
                        'sqlalchemy',
                        'pyproj',                        
                        ],
      url='https://github.com/valheiafr/gripit',
      license='Apache',
      author='Valentin Pasche',
      author_email='valentin.pasche@hefr.ch',
      description='Projet de recherche Ra&D HES-SO, distibution du code',
      packages=['gripit', 'gripit.DataBase', 'gripit.Physics'],
     )